### ISSUE TITLE
Trial License

### ISSUE THREAD

**Issue by gmpopplewell** [waldo1001/Waldo.Model.Tools#11]
Good afternoon, I hope we're all well?

Slightly off topic for this but i don't seem to be able to get a trial license key from https://www.ifacto.be/en/revisionrequest, i've been trying quite a lot for the last 3 or 4 days but the issue persists.  it just gives the error "Something went wrong. Try again."

any assistance would be greatly appreciated

**Comment by waldo1001** [comment]
This should be working again.. .

**Comment by gmpopplewell** [comment]
That's all working, many thanks!!
