### ISSUE TITLE
Licence request fails

### ISSUE THREAD

**Issue by Kowa63** [waldo1001/Waldo.Model.Tools#2]
Hi Waldo,
great initiative to provide such a tool.
I tried to request a licence (with both FF and IE) several times but all I'm getting is this:
"Something went wrong. Try again." 
![grafik](https://user-images.githubusercontent.com/16236672/53475913-75962380-3a71-11e9-821e-f0e445299856.png)

**Comment by waldo1001** [comment]
Thanks for reporting, Kai, we're looking into it!

**Comment by BartBourgeois** [comment]
Could you please try again. We enabled some extra monitoring on the service.

**Comment by Kowa63** [comment]
I found out the reason. We have an ampersand in our company name (… & Co. KG, quite common in Germany ;-) ), after I deleted that and simplified the rest of the name it worked.

**Comment by waldo1001** [comment]
great :-)
