### ISSUE TITLE
Check Licence failed even if the licence.key is in the folder

### ISSUE THREAD

**Issue by matsmen** [waldo1001/Waldo.Model.Tools#8]
I have activated the Trial of the NavModelToolsAPI.dll and copy the licence file in The Magic folder, but when I am using the commande Check-Licence to validate if the licence is ok, I have this message saying that it is expired :
Check-License : EXPIRED
At line:1 char:1
+ Check-License
+ ~~~~~~~~~~~~~
+ CategoryInfo          : ConnectionError: (System.Exceptio...ProcessRecord():Exception) [Check-License], Exception
+ FullyQualifiedErrorId : LICENSE,NavModelToolsAPI.CmdLets.CheckLicense

**Comment by waldo1001** [comment]
Seems to be an issue indeed – will have a look ..

**Comment by waldo1001** [comment]
Should be fixed!  Download a new copy of the "The Magic" folder!
